#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const args = process.argv.slice(2);
const command = args[0];

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      // Skip story files
      if (entry.name.includes('.stories.')) continue;
      fs.copyFileSync(srcPath, destPath);
      log(`  + ${entry.name}`, 'green');
    }
  }
}

function installDependencies(cwd) {
  const dependencies = ['antd', '@ant-design/icons', 'dayjs', 'clsx'];
  
  log('\n📦 Installing dependencies...', 'yellow');
  
  try {
    execSync(`npm install ${dependencies.join(' ')}`, {
      cwd: cwd,
      stdio: 'inherit'
    });
    log('\n✅ Dependencies installed!', 'green');
    return true;
  } catch (error) {
    log('\n❌ Failed to install dependencies', 'red');
    log('Please run manually:', 'yellow');
    log(`npm install ${dependencies.join(' ')}`, 'blue');
    return false;
  }
}

function init() {
  const cwd = process.cwd();
  const targetDir = path.join(cwd, 'src', 'components', 'antd');
  
  log('\n🚀 Antd Components Generator\n', 'cyan');
  
  // Find the package directory
  const packageDir = path.dirname(__dirname);
  const srcDir = path.join(packageDir, 'src');
  
  // Check if src exists
  if (!fs.existsSync(srcDir)) {
    log('❌ Source files not found!', 'red');
    return;
  }

  // Copy components
  log('📁 Creating components...', 'yellow');
  const componentsDir = path.join(srcDir, 'components');
  if (fs.existsSync(componentsDir)) {
    copyDir(componentsDir, targetDir);
  }

  // Copy utils
  log('\n📁 Creating utils...', 'yellow');
  const utilsDir = path.join(srcDir, 'utils');
  const targetUtilsDir = path.join(cwd, 'src', 'utils');
  if (fs.existsSync(utilsDir)) {
    copyDir(utilsDir, targetUtilsDir);
  }

  // Copy hooks
  log('\n📁 Creating hooks...', 'yellow');
  const hooksDir = path.join(srcDir, 'hooks');
  const targetHooksDir = path.join(cwd, 'src', 'hooks');
  if (fs.existsSync(hooksDir)) {
    copyDir(hooksDir, targetHooksDir);
  }

  // Create index.ts
  const indexContent = `// Antd Custom Components
// Generated by antd-components CLI

export * from './antd/Form';
export * from './antd/Layout';
export * from './antd/Table';
export * from './antd/Feedback';
export * from './antd/General';
export * from './antd/Navigation';
export * from './antd/DataEntry';
export * from './antd/DataDisplay';
export * from './antd/Other';
`;

  const componentsIndexPath = path.join(cwd, 'src', 'components');
  if (!fs.existsSync(componentsIndexPath)) {
    fs.mkdirSync(componentsIndexPath, { recursive: true });
  }
  
  const indexPath = path.join(componentsIndexPath, 'index.ts');
  fs.writeFileSync(indexPath, indexContent);
  log(`\n  + index.ts`, 'green');

  log('\n✅ Components created!', 'green');
  
  // Auto install dependencies
  installDependencies(cwd);
  
  log('\n📝 Usage:', 'cyan');
  log(`import { CustomInput, CustomTable } from './components';`, 'blue');
  log('');
}

function help() {
  log('\n🎨 Antd Components CLI\n', 'cyan');
  log('Usage:', 'yellow');
  log('  npx antd-components init    Generate all components');
  log('  npx antd-components help    Show help\n');
}

// Main
switch (command) {
  case 'init':
    init();
    break;
  case 'help':
  case '--help':
  case '-h':
    help();
    break;
  default:
    help();
}
