#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const command = args[0];

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      // Skip story files
      if (entry.name.includes('.stories.')) continue;
      fs.copyFileSync(srcPath, destPath);
      log(`  ✓ ${destPath}`, 'green');
    }
  }
}

function init() {
  const cwd = process.cwd();
  const targetDir = path.join(cwd, 'src', 'components', 'antd');
  
  log('\n🚀 Antd Components Generator\n', 'cyan');
  log('กำลังสร้าง components...', 'yellow');
  
  // Find the package directory
  const packageDir = path.dirname(__dirname);
  const srcDir = path.join(packageDir, 'src');
  
  // Copy components
  const componentsDir = path.join(srcDir, 'components');
  if (fs.existsSync(componentsDir)) {
    copyDir(componentsDir, targetDir);
  }

  // Copy utils
  const utilsDir = path.join(srcDir, 'utils');
  const targetUtilsDir = path.join(cwd, 'src', 'utils');
  if (fs.existsSync(utilsDir)) {
    log('\nกำลังสร้าง utils...', 'yellow');
    copyDir(utilsDir, targetUtilsDir);
  }

  // Copy hooks
  const hooksDir = path.join(srcDir, 'hooks');
  const targetHooksDir = path.join(cwd, 'src', 'hooks');
  if (fs.existsSync(hooksDir)) {
    log('\nกำลังสร้าง hooks...', 'yellow');
    copyDir(hooksDir, targetHooksDir);
  }

  // Create index.ts for easy imports
  const indexContent = `// Antd Custom Components
// Generated by antd-components CLI

// Form Components
export * from './antd/Form';

// Layout Components  
export * from './antd/Layout';

// Table Components
export * from './antd/Table';

// Feedback Components
export * from './antd/Feedback';

// General Components
export * from './antd/General';

// Navigation Components
export * from './antd/Navigation';

// Data Entry Components
export * from './antd/DataEntry';

// Data Display Components
export * from './antd/DataDisplay';

// Other Components
export * from './antd/Other';
`;

  const indexPath = path.join(cwd, 'src', 'components', 'index.ts');
  fs.writeFileSync(indexPath, indexContent);
  log(`  ✓ ${indexPath}`, 'green');

  log('\n✅ สร้าง components เสร็จสิ้น!\n', 'green');
  
  log('📦 Dependencies ที่ต้องติดตั้ง:', 'cyan');
  log('npm install antd @ant-design/icons dayjs clsx\n', 'yellow');
  
  log('📝 วิธีใช้งาน:', 'cyan');
  log(`import { CustomInput, CustomTable, CustomCard } from '@/components';`, 'blue');
  log('');
}

function help() {
  log('\n🎨 Antd Components CLI\n', 'cyan');
  log('Usage:', 'yellow');
  log('  npx antd-components init    สร้าง component ทั้งหมด');
  log('  npx antd-components help    แสดงคำสั่ง\n');
}

// Main
switch (command) {
  case 'init':
    init();
    break;
  case 'help':
  case '--help':
  case '-h':
    help();
    break;
  default:
    help();
}

